'use client'
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _admin_layout_shell from './admin-layout-shell.bones.json'
import _club_management_layout_shell from './club-management-layout-shell.bones.json'
import _admin_dashboard_loading from './admin-dashboard-loading.bones.json'
import _admin_users_table_loading from './admin-users-table-loading.bones.json'
import _admin_launch_interest_loading from './admin-launch-interest-loading.bones.json'
import _admin_monitoring_loading from './admin-monitoring-loading.bones.json'
import _club_list_loading from './club-list-loading.bones.json'
import _club_feed_loading from './club-feed-loading.bones.json'
import _club_rides_loading from './club-rides-loading.bones.json'
import _club_marketplace_loading from './club-marketplace-loading.bones.json'
import _club_detail_loading from './club-detail-loading.bones.json'
import _club_manage_loading from './club-manage-loading.bones.json'
import _marketplace_listing_detail_loading from './marketplace-listing-detail-loading.bones.json'
import _profile_view_loading from './profile-view-loading.bones.json'
import _profile_edit_loading from './profile-edit-loading.bones.json'

configureBoneyard({
  color: '#eceff3',
  darkColor: '#2a2f36',
  animate: 'shimmer',
  shimmerColor: '#f7f9fc',
  darkShimmerColor: '#3a424d',
  speed: '1.8s',
  shimmerAngle: 110,
  transition: 220,
})

const generatedBones = {
  'admin-layout-shell': _admin_layout_shell,
  'club-management-layout-shell': _club_management_layout_shell,
  'admin-dashboard-loading': _admin_dashboard_loading,
  'admin-users-table-loading': _admin_users_table_loading,
  'admin-launch-interest-loading': _admin_launch_interest_loading,
  'admin-monitoring-loading': _admin_monitoring_loading,
  'club-list-loading': _club_list_loading,
  'club-feed-loading': _club_feed_loading,
  'club-rides-loading': _club_rides_loading,
  'club-marketplace-loading': _club_marketplace_loading,
  'club-detail-loading': _club_detail_loading,
  'club-manage-loading': _club_manage_loading,
  'marketplace-listing-detail-loading': _marketplace_listing_detail_loading,
  'profile-view-loading': _profile_view_loading,
  'profile-edit-loading': _profile_edit_loading,
}

export { generatedBones }

registerBones(generatedBones as Record<string, any>)
